# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_LoginWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(813, 509)
        #隐藏边框
        MainWindow.setWindowFlags(QtCore.Qt.FramelessWindowHint)
        MainWindow.setAttribute(QtCore.Qt.WA_TranslucentBackground)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.login_pic = QtWidgets.QLabel(self.centralwidget)
        self.login_pic.setGeometry(QtCore.QRect(5, 10, 340, 490))
        self.login_pic.setStyleSheet("border-image: url(:/images/resources/images/register.jpg);\n"
"border-top-left-radius:30px;\n"
"border-bottom-left-radius:30px;")
        self.login_pic.setText("")
        self.login_pic.setObjectName("login_pic")
        self.login_items = QtWidgets.QLabel(self.centralwidget)
        self.login_items.setGeometry(QtCore.QRect(345, 10, 461, 490))
        self.login_items.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-top-right-radius:30px;\n"
"border-bottom-right-radius:30px;")
        self.login_items.setText("")
        self.login_items.setObjectName("login_items")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(425, 60, 281, 81))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.login_or_register = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.login_or_register.setContentsMargins(0, 0, 0, 0)
        self.login_or_register.setSpacing(0)
        self.login_or_register.setObjectName("login_or_register")
        self.login_btn = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.login_btn.setFont(font)
        self.login_btn.setStyleSheet("#login_btn{\n"
"    border:none;\n"
"}\n"
"\n"
"#login_btn:focus{\n"
"    color:rgb(186,186,186);\n"
"}")
        self.login_btn.setObjectName("login_btn")
        self.login_or_register.addWidget(self.login_btn)
        self.line = QtWidgets.QFrame(self.horizontalLayoutWidget)
        self.line.setMaximumSize(QtCore.QSize(5, 45))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.line.setFont(font)
        self.line.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line.setLineWidth(2)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setObjectName("line")
        self.login_or_register.addWidget(self.line)
        self.register_btn = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.register_btn.setFont(font)
        self.register_btn.setStyleSheet("#register_btn{\n"
"    border:none;\n"
"}\n"
"\n"
"#register_btn:focus{\n"
"    color:rgb(186,186,186);\n"
"}")
        self.register_btn.setObjectName("register_btn")
        self.login_or_register.addWidget(self.register_btn)
        self.close_btn = QtWidgets.QPushButton(self.centralwidget)
        self.close_btn.setGeometry(QtCore.QRect(765, 20, 25, 25))
        self.close_btn.setStyleSheet("border-image: url(:/icons/resources/icons/close.png);\n"
"border: none;")
        self.close_btn.setText("")
        self.close_btn.setIconSize(QtCore.QSize(18, 18))
        self.close_btn.setObjectName("close_btn")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setGeometry(QtCore.QRect(390, 150, 371, 341))
        self.stackedWidget.setStyleSheet("border : none;")
        self.stackedWidget.setObjectName("stackedWidget")
        self.page_register = QtWidgets.QWidget()
        self.page_register.setObjectName("page_register")
        self.register_username_input = QtWidgets.QLineEdit(self.page_register)
        self.register_username_input.setEnabled(True)
        self.register_username_input.setGeometry(QtCore.QRect(0, 10, 369, 55))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(5)
        sizePolicy.setHeightForWidth(self.register_username_input.sizePolicy().hasHeightForWidth())
        self.register_username_input.setSizePolicy(sizePolicy)
        self.register_username_input.setMinimumSize(QtCore.QSize(0, 0))
        self.register_username_input.setMaximumSize(QtCore.QSize(16777215, 55))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setKerning(False)
        self.register_username_input.setFont(font)
        self.register_username_input.setStyleSheet("border:1px solid rgb(0,0,0);\n"
"padding-left:3px;\n"
"border-radius:8px;")
        self.register_username_input.setObjectName("register_username_input")
        self.register_email_input = QtWidgets.QLineEdit(self.page_register)
        self.register_email_input.setEnabled(True)
        self.register_email_input.setGeometry(QtCore.QRect(0, 70, 369, 55))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.register_email_input.sizePolicy().hasHeightForWidth())
        self.register_email_input.setSizePolicy(sizePolicy)
        self.register_email_input.setMinimumSize(QtCore.QSize(0, 8))
        self.register_email_input.setMaximumSize(QtCore.QSize(16777215, 55))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setKerning(True)
        self.register_email_input.setFont(font)
        self.register_email_input.setStyleSheet("border:1px solid rgb(0,0,0);\n"
"border-radius:8px;\n"
"padding-left:3px;")
        self.register_email_input.setObjectName("register_email_input")
        self.register_pwd_input = QtWidgets.QLineEdit(self.page_register)
        self.register_pwd_input.setEnabled(True)
        self.register_pwd_input.setGeometry(QtCore.QRect(0, 130, 369, 55))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.register_pwd_input.sizePolicy().hasHeightForWidth())
        self.register_pwd_input.setSizePolicy(sizePolicy)
        self.register_pwd_input.setMinimumSize(QtCore.QSize(0, 0))
        self.register_pwd_input.setMaximumSize(QtCore.QSize(16777215, 55))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setKerning(False)
        self.register_pwd_input.setFont(font)
        self.register_pwd_input.setStyleSheet("border:1px solid rgb(0,0,0);\n"
"border-radius:8px;\n"
"padding-left:3px;")
        self.register_pwd_input.setObjectName("register_pwd_input")
        self.register_pwd_input_confirm = QtWidgets.QLineEdit(self.page_register)
        self.register_pwd_input_confirm.setEnabled(True)
        self.register_pwd_input_confirm.setGeometry(QtCore.QRect(0, 190, 369, 55))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.register_pwd_input_confirm.sizePolicy().hasHeightForWidth())
        self.register_pwd_input_confirm.setSizePolicy(sizePolicy)
        self.register_pwd_input_confirm.setMinimumSize(QtCore.QSize(0, 8))
        self.register_pwd_input_confirm.setMaximumSize(QtCore.QSize(16777215, 55))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setKerning(True)
        self.register_pwd_input_confirm.setFont(font)
        self.register_pwd_input_confirm.setStyleSheet("border:1px solid rgb(0,0,0);\n"
"border-radius:8px;\n"
"padding-left:3px;")
        self.register_pwd_input_confirm.setObjectName("register_pwd_input_confirm")
        self.register_confirm_btn = QtWidgets.QPushButton(self.page_register)
        self.register_confirm_btn.setGeometry(QtCore.QRect(0, 260, 369, 50))
        self.register_confirm_btn.setMinimumSize(QtCore.QSize(0, 50))
        self.register_confirm_btn.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.register_confirm_btn.setStyleSheet("#register_confirm_btn{\n"
"    background-color:rgb(0,0,0);\n"
"    color:rgb(255,255,255);\n"
"    border:3px solid rgb(0,0,0);\n"
"    border-radius:8px;\n"
"}\n"
"\n"
"#register_confirm_btn:hover{\n"
"    background-color:rgb(255,255,255);\n"
"    color:rgb(0,0,0);\n"
"}\n"
"#register_confirm_btn:pressed{\n"
"    padding-top: 5px;\n"
"    padding-left:5px;\n"
"}\n"
"")
        self.register_confirm_btn.setObjectName("register_confirm_btn")
        self.register_info = QtWidgets.QLabel(self.page_register)
        self.register_info.setGeometry(QtCore.QRect(0, 320, 371, 16))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(11)
        font.setItalic(True)
        self.register_info.setFont(font)
        self.register_info.setStyleSheet("color: rgb(255, 0, 0);")
        self.register_info.setObjectName("register_info")
        self.stackedWidget.addWidget(self.page_register)
        self.page_login = QtWidgets.QWidget()
        self.page_login.setObjectName("page_login")
        self.username_input = QtWidgets.QLineEdit(self.page_login)
        self.username_input.setEnabled(True)
        self.username_input.setGeometry(QtCore.QRect(0, 20, 369, 55))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.username_input.sizePolicy().hasHeightForWidth())
        self.username_input.setSizePolicy(sizePolicy)
        self.username_input.setMinimumSize(QtCore.QSize(7, 6))
        self.username_input.setMaximumSize(QtCore.QSize(16777215, 55))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setKerning(False)
        self.username_input.setFont(font)
        self.username_input.setStyleSheet("border:1px solid rgb(0,0,0);\n"
"border-radius:8px;\n"
"padding-left:3px;")
        self.username_input.setObjectName("username_input")
        self.password_input = QtWidgets.QLineEdit(self.page_login)
        self.password_input.setEnabled(True)
        self.password_input.setGeometry(QtCore.QRect(0, 110, 369, 55))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.password_input.sizePolicy().hasHeightForWidth())
        self.password_input.setSizePolicy(sizePolicy)
        self.password_input.setMinimumSize(QtCore.QSize(0, 0))
        self.password_input.setMaximumSize(QtCore.QSize(16777215, 55))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setKerning(False)
        self.password_input.setFont(font)
        self.password_input.setStyleSheet("border:1px solid rgb(0,0,0);\n"
"border-radius:8px;\n"
"padding-left:3px;")
        self.password_input.setEchoMode(QtWidgets.QLineEdit.Password)
        self.password_input.setObjectName("password_input")
        self.remember_box = QtWidgets.QCheckBox(self.page_login)
        self.remember_box.setGeometry(QtCore.QRect(0, 180, 369, 30))
        self.remember_box.setMinimumSize(QtCore.QSize(0, 30))
        self.remember_box.setIconSize(QtCore.QSize(16, 16))
        self.remember_box.setObjectName("remember_box")
        self.login_confirm_btn = QtWidgets.QPushButton(self.page_login)
        self.login_confirm_btn.setGeometry(QtCore.QRect(0, 220, 369, 50))
        self.login_confirm_btn.setMinimumSize(QtCore.QSize(0, 50))
        self.login_confirm_btn.setStyleSheet("#login_confirm_btn{\n"
"    background-color:rgb(0,0,0);\n"
"    color:rgb(255,255,255);\n"
"    border:3px solid rgb(0,0,0);\n"
"    border-radius:8px;\n"
"}\n"
"\n"
"#login_confirm_btn:hover{\n"
"    background-color:rgb(255,255,255);\n"
"    color:rgb(0,0,0);\n"
"}\n"
"#login_confirm_btn:pressed{\n"
"    padding-top: 5px;\n"
"    padding-left:5px;\n"
"}\n"
"")
        self.login_confirm_btn.setObjectName("login_confirm_btn")
        self.login_info = QtWidgets.QLabel(self.page_login)
        self.login_info.setGeometry(QtCore.QRect(0, 290, 371, 16))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(11)
        font.setItalic(True)
        self.login_info.setFont(font)
        self.login_info.setStyleSheet("color: rgb(255, 0, 0);")
        self.login_info.setObjectName("login_info")
        self.stackedWidget.addWidget(self.page_login)
        self.login_items.raise_()
        self.login_pic.raise_()
        self.horizontalLayoutWidget.raise_()
        self.close_btn.raise_()
        self.stackedWidget.raise_()

        # 增加阴影  
        self.login_pic.setGraphicsEffect( QtWidgets.QGraphicsDropShadowEffect(blurRadius=25,xOffset=0,yOffset=0))
        self.login_items.setGraphicsEffect( QtWidgets.QGraphicsDropShadowEffect(blurRadius=25,xOffset=0,yOffset=0))
        self.login_confirm_btn.setGraphicsEffect( QtWidgets.QGraphicsDropShadowEffect(blurRadius=25,xOffset=0,yOffset=0))
        self.register_confirm_btn.setGraphicsEffect( QtWidgets.QGraphicsDropShadowEffect(blurRadius=25,xOffset=0,yOffset=0))
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        self.close_btn.clicked.connect(MainWindow.close) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.login_btn.setText(_translate("MainWindow", "Login"))
        self.register_btn.setText(_translate("MainWindow", "Register"))
        self.register_username_input.setPlaceholderText(_translate("MainWindow", "UserName"))
        self.register_email_input.setPlaceholderText(_translate("MainWindow", "Email"))
        self.register_pwd_input.setPlaceholderText(_translate("MainWindow", "PassWord"))
        self.register_pwd_input_confirm.setPlaceholderText(_translate("MainWindow", "Confirm PassWord"))
        self.register_confirm_btn.setText(_translate("MainWindow", "Confirm"))
        self.register_info.setText(_translate("MainWindow", "Something to Info !"))
        self.username_input.setPlaceholderText(_translate("MainWindow", "UserName"))
        self.password_input.setPlaceholderText(_translate("MainWindow", "PassWord"))
        self.remember_box.setText(_translate("MainWindow", "remember"))
        self.login_confirm_btn.setText(_translate("MainWindow", "Confrim"))
        self.login_info.setText(_translate("MainWindow", "Something to Info !"))
import resources_rc
