# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(839, 531)
        #隐藏边框
        MainWindow.setWindowFlags(QtCore.Qt.FramelessWindowHint)
        MainWindow.setAttribute(QtCore.Qt.WA_TranslucentBackground)
        font = QtGui.QFont()
        font.setFamily("华文隶书")
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(10, 10, 821, 512))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setGeometry(QtCore.QRect(0, 0, 821, 41))
        self.frame_2.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-top-right-radius:20px;\n"
"border-top-left-radius:20px;")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.logo = QtWidgets.QLabel(self.frame_2)
        self.logo.setGeometry(QtCore.QRect(20, 5, 41, 31))
        self.logo.setStyleSheet("image: url(:/icons/resources/icons/LexiLab.png);")
        self.logo.setText("")
        self.logo.setObjectName("logo")
        self.caption = QtWidgets.QLabel(self.frame_2)
        self.caption.setGeometry(QtCore.QRect(70, 12, 61, 16))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.caption.setFont(font)
        self.caption.setObjectName("caption")
        self.close_btn = QtWidgets.QPushButton(self.frame_2)
        self.close_btn.setGeometry(QtCore.QRect(790, 10, 25, 25))
        self.close_btn.setStyleSheet("border-image: url(:/icons/resources/icons/close.png);")
        self.close_btn.setText("")
        self.close_btn.setObjectName("close_btn")
        self.logout = QtWidgets.QPushButton(self.frame_2)
        self.logout.setGeometry(QtCore.QRect(730, 10, 25, 25))
        self.logout.setStyleSheet("border-image: url(:/icons/resources/icons/logout.png);")
        self.logout.setText("")
        self.logout.setObjectName("logout")
        self.minimise = QtWidgets.QPushButton(self.frame_2)
        self.minimise.setGeometry(QtCore.QRect(760, 10, 25, 25))
        self.minimise.setStyleSheet("border-image: url(:/icons/resources/icons/minimise.png);")
        self.minimise.setText("")
        self.minimise.setObjectName("minimise")
        self.frame_3 = QtWidgets.QFrame(self.frame)
        self.frame_3.setGeometry(QtCore.QRect(-1, 39, 51, 471))
        self.frame_3.setStyleSheet("background-color: rgba(255, 248, 240,128);\n"
"border-bottom-left-radius:20px;\n"
"border-top-right-radius:20px;\n"
"border-bottom-right-radius:20px;\n"
"border-top-left-radius:20px;")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.person_btn = QtWidgets.QPushButton(self.frame_3)
        self.person_btn.setGeometry(QtCore.QRect(10, 410, 32, 32))
        self.person_btn.setStyleSheet("border:none;\n"
"border-image: url(:/icons/resources/icons/person.png);\n"
"background-color: rgba(255, 255, 255,0);")
        self.person_btn.setText("")
        self.person_btn.setObjectName("person_btn")
        self.home_btn = QtWidgets.QPushButton(self.frame_3)
        self.home_btn.setGeometry(QtCore.QRect(10, 30, 32, 32))
        self.home_btn.setStyleSheet("border:none;\n"
"\n"
"border-image: url(:/icons/resources/icons/home.png);\n"
"background-color: rgba(255, 255, 255,0);")
        self.home_btn.setText("")
        self.home_btn.setObjectName("home_btn")
        self.query_btn = QtWidgets.QPushButton(self.frame_3)
        self.query_btn.setGeometry(QtCore.QRect(10, 80, 32, 32))
        self.query_btn.setStyleSheet("border:none;\n"
"border-image:url(:/icons/resources/icons/query.png);\n"
"background-color: rgba(255, 255, 255,0);")
        self.query_btn.setText("")
        self.query_btn.setObjectName("query_btn")
        self.stackedWidget = QtWidgets.QStackedWidget(self.frame)
        self.stackedWidget.setGeometry(QtCore.QRect(0, 40, 821, 471))
        self.stackedWidget.setStyleSheet("border-image: url(:/images/resources/images/home_bg.jpg);\n"
"border-bottom-right-radius :20px;\n"
"border-bottom-left-radius :20px;\n"
"\n"
"QStackedWidget:: QToolButton {\n"
"background-color: rgba(0,0,0,0);\n"
"}\n"
"")
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.term_input = QtWidgets.QTextEdit(self.page)
        self.term_input.setGeometry(QtCore.QRect(110, 20, 641, 121))
        self.term_input.setAutoFillBackground(False)
        self.term_input.setStyleSheet("border-image: none;\n"
"background-color: rgba(183, 183, 183,160);\n"
"border-radius: 10px;\n"
"color: rgba(255, 255, 255,255);\n"
"font: 16pt \"Times New Roman\";\n"
"\n"
"padding-top: 5px;\n"
"padding-right: 5px;\n"
"padding-bottom: 5px;\n"
"padding-left: 5px;\n"
"")
        self.term_input.setInputMethodHints(QtCore.Qt.ImhMultiLine)
        self.term_input.setFrameShadow(QtWidgets.QFrame.Plain)
        self.term_input.setAcceptRichText(False)
        self.term_input.setObjectName("term_input")
        self.explain_input = QtWidgets.QTextEdit(self.page)
        self.explain_input.setGeometry(QtCore.QRect(110, 170, 641, 181))
        self.explain_input.setStyleSheet("border-image: none;\n"
"background-color: rgba(183, 183, 183,160);\n"
"border-radius: 10px;\n"
"color: rgba(255, 255, 255,255);\n"
"font: 16pt \"Times New Roman\";\n"
"\n"
"padding-top: 5px;\n"
"padding-right: 5px;\n"
"padding-bottom: 5px;\n"
"padding-left: 5px;")
        self.explain_input.setTabChangesFocus(True)
        self.explain_input.setAcceptRichText(False)
        self.explain_input.setObjectName("explain_input")
        self.commit_btn = QtWidgets.QPushButton(self.page)
        self.commit_btn.setGeometry(QtCore.QRect(720, 330, 101, 131))
        self.commit_btn.setStyleSheet("border-image: url(:/images/resources/images/background.png);")
        self.commit_btn.setText("")
        self.commit_btn.setObjectName("commit_btn")
        self.tips = QtWidgets.QLabel(self.page)
        self.tips.setGeometry(QtCore.QRect(240, 390, 481, 51))
        font = QtGui.QFont()
        font.setFamily("隶书")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.tips.setFont(font)
        self.tips.setStyleSheet("border-image: none;\n"
"background-color: rgba(183, 183, 183,160);\n"
"border-top-left-radius: 10px;\n"
"border-bottom-left-radius: 10px;\n"
"\n"
"border-top-right-radius: 16px;\n"
"border-bottom-right-radius: 35px;\n"
"color: rgba(255, 255, 255,255);\n"
"font: 16pt \"隶书\";\n"
"\n"
"padding-right: 5px;\n"
"\n"
"padding-left: 5px;")
        self.tips.setObjectName("tips")
        self.stackedWidget.addWidget(self.page)
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.query_input = QtWidgets.QTextEdit(self.page_3)
        self.query_input.setGeometry(QtCore.QRect(130, 40, 551, 51))
        self.query_input.setAutoFillBackground(False)
        self.query_input.setStyleSheet("border-image: none;\n"
"background-color: rgba(183, 183, 183,160);\n"
"border-radius: 10px;\n"
"border-top-right-radius: 0px;\n"
"border-bottom-right-radius: 0px;\n"
"color: rgba(255, 255, 255,255);\n"
"font: 16pt \"Times New Roman\";\n"
"\n"
"padding-top: 10px;\n"
"padding-right: 5px;\n"
"padding-bottom: 5px;\n"
"padding-left: 5px;\n"
"")
        self.query_input.setInputMethodHints(QtCore.Qt.ImhNone)
        self.query_input.setFrameShadow(QtWidgets.QFrame.Plain)
        self.query_input.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.query_input.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.query_input.setAcceptRichText(False)
        self.query_input.setObjectName("query_input")
        self.widget = QtWidgets.QWidget(self.page_3)
        self.widget.setGeometry(QtCore.QRect(680, 40, 52, 51))
        self.widget.setStyleSheet("border-image: none;\n"
"\n"
"background-color: rgba(183, 183, 183,160);\n"
"border-radius: 10px;\n"
"border-top-left-radius:0px;\n"
"border-bottom-left-radius:0px;\n"
"color: rgba(255, 255, 255,255);\n"
"font: 16pt \"Times New Roman\";\n"
"\n"
"padding-top: 10px;\n"
"padding-right: 10px;\n"
"padding-bottom: 10px;\n"
"padding-left: 10px;\n"
"")
        self.widget.setObjectName("widget")
        self.search_btn = QtWidgets.QPushButton(self.widget)
        self.search_btn.setGeometry(QtCore.QRect(10, 9, 36, 36))
        self.search_btn.setStyleSheet("border-image: none;\n"
"border-image: url(:/icons/resources/icons/query_btn.png);\n"
"background-color: rgba(183, 183, 183,0);\n"
"border-radius: 10px;\n"
"border-top-right-radius:0px;\n"
"border-bottom-right-radius:0px;\n"
"color: rgba(255, 255, 255,255);\n"
"font: 16pt \"Times New Roman\";\n"
"\n"
"padding-top: 10px;\n"
"padding-right: 10px;\n"
"padding-bottom: 10px;\n"
"padding-left: 10px;\n"
"")
        self.search_btn.setText("")
        self.search_btn.setObjectName("search_btn")
        self.query_output = QtWidgets.QTextEdit(self.page_3)
        self.query_output.setGeometry(QtCore.QRect(110, 140, 641, 281))
        self.query_output.setStyleSheet("border-image: none;\n"
"background-color: rgba(183, 183, 183,160);\n"
"border-radius: 10px;\n"
"color: rgba(255, 255, 255,255);\n"
"font: 16pt \"Times New Roman\";\n"
"\n"
"padding-top: 5px;\n"
"padding-right: 5px;\n"
"padding-bottom: 5px;\n"
"padding-left: 5px;")
        self.query_output.setTabChangesFocus(True)
        self.query_output.setAcceptRichText(False)
        self.query_output.setPlaceholderText("")
        self.query_output.setObjectName("query_output")
        self.stackedWidget.addWidget(self.page_3)
        self.page_4 = QtWidgets.QWidget()
        self.page_4.setObjectName("page_4")
        self.show_record_num = QtWidgets.QLabel(self.page_4)
        self.show_record_num.setGeometry(QtCore.QRect(370, 170, 111, 41))
        self.show_record_num.setStyleSheet("border-image: none;\n"
"background-color: rgba(183, 183, 183,160);\n"
"border-radius: 10px;\n"
"\n"
"color: rgba(255, 255, 255,255);\n"
"font: 16pt \"Times New Roman\";\n"
"\n"
"padding-top: 5px;\n"
"padding-right: 5px;\n"
"padding-bottom: 5px;\n"
"padding-left: 5px;")
        self.show_record_num.setAlignment(QtCore.Qt.AlignCenter)
        self.show_record_num.setObjectName("show_record_num")
        self.show_username = QtWidgets.QLabel(self.page_4)
        self.show_username.setGeometry(QtCore.QRect(280, 40, 301, 61))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.show_username.setFont(font)
        self.show_username.setStyleSheet("border-image: none;\n"
"background-color: rgba(183, 183, 183,160);\n"
"border-radius: 10px;\n"
"\n"
"color: rgba(255, 255, 255,255);\n"
"font: 20pt \"Times New Roman\";\n"
"\n"
"padding-top: 5px;\n"
"padding-right: 5px;\n"
"padding-bottom: 5px;\n"
"padding-left: 5px;")
        self.show_username.setTextFormat(QtCore.Qt.PlainText)
        self.show_username.setAlignment(QtCore.Qt.AlignCenter)
        self.show_username.setObjectName("show_username")
        self.show_email = QtWidgets.QLabel(self.page_4)
        self.show_email.setGeometry(QtCore.QRect(280, 120, 301, 31))
        self.show_email.setStyleSheet("border-image: none;\n"
"background-color: rgba(183, 183, 183,160);\n"
"border-radius: 10px;\n"
"\n"
"color: rgba(255, 255, 255,255);\n"
"font: 12pt \"Times New Roman\";\n"
"\n"
"padding-top: 5px;\n"
"padding-right: 5px;\n"
"padding-bottom: 5px;\n"
"padding-left: 5px;")
        self.show_email.setAlignment(QtCore.Qt.AlignCenter)
        self.show_email.setObjectName("show_email")
        self.shownum_0 = QtWidgets.QGraphicsView(self.page_4)
        self.shownum_0.setGeometry(QtCore.QRect(150, 260, 68, 150))
        self.shownum_0.setStyleSheet("border-radius: 10px;\n"
"border-image: none;\n"
"background-color: rgba(255, 255, 255,0);\n"
"")
        self.shownum_0.setObjectName("shownum_0")
        self.shownum_1 = QtWidgets.QGraphicsView(self.page_4)
        self.shownum_1.setGeometry(QtCore.QRect(250, 260, 68, 150))
        self.shownum_1.setStyleSheet("border-radius: 10px;\n"
"border-image: none;\n"
"background-color: rgba(255, 255, 255,0);\n"
"")
        self.shownum_1.setObjectName("shownum_1")
        self.shownum_2 = QtWidgets.QGraphicsView(self.page_4)
        self.shownum_2.setGeometry(QtCore.QRect(350, 260, 68, 150))
        self.shownum_2.setStyleSheet("border-radius: 10px;\n"
"border-image: none;\n"
"background-color: rgba(255, 255, 255,0);\n"
"")
        self.shownum_2.setObjectName("shownum_2")
        self.shownum_3 = QtWidgets.QGraphicsView(self.page_4)
        self.shownum_3.setGeometry(QtCore.QRect(450, 260, 68, 150))
        self.shownum_3.setStyleSheet("border-radius: 10px;\n"
"border-image: none;\n"
"background-color: rgba(255, 255, 255,0);\n"
"")
        self.shownum_3.setObjectName("shownum_3")
        self.shownum_4 = QtWidgets.QGraphicsView(self.page_4)
        self.shownum_4.setGeometry(QtCore.QRect(550, 260, 68, 150))
        self.shownum_4.setStyleSheet("border-radius: 10px;\n"
"border-image: none;\n"
"background-color: rgba(255, 255, 255,0);\n"
"")
        self.shownum_4.setObjectName("shownum_4")
        self.shownum_5 = QtWidgets.QGraphicsView(self.page_4)
        self.shownum_5.setGeometry(QtCore.QRect(650, 260, 68, 150))
        self.shownum_5.setStyleSheet("border-radius: 10px;\n"
"border-image: none;\n"
"background-color: rgba(255, 255, 255,0);\n"
"")
        self.shownum_5.setObjectName("shownum_5")
        self.stackedWidget.addWidget(self.page_4)
        self.frame_2.raise_()
        self.stackedWidget.raise_()
        self.frame_3.raise_()

        self.commit_btn.setGraphicsEffect( QtWidgets.QGraphicsDropShadowEffect(blurRadius=25,xOffset=0,yOffset=0))

        # 改变默认滚动条
        self.term_input_bar = QtWidgets.QScrollBar()
        self.term_input_bar.setStyleSheet("""
            QScrollBar:vertical {
                border-width: 0px;
                border: none;
                background:rgba(64, 65, 79, 0);
                width:12px;
                margin: 0px 0px 0px 0px;
            }
            QScrollBar::handle:vertical {
                background: qlineargradient(x1:0, y1:0, x2:1, y2:0,
                stop: 0 #afc779, stop: 0.5 #afc779, stop:1 #afc779);
                min-height: 20px;
                max-height: 20px;
                margin: 0 0px 0 0px;
                border-radius: 6px;
            }
            QScrollBar::add-line:vertical {
                background: qlineargradient(x1:0, y1:0, x2:1, y2:0,
                stop: 0 rgba(64, 65, 79, 0), stop: 0.5 rgba(64, 65, 79, 0),  stop:1 rgba(64, 65, 79, 0));
                height: 0px;
                border: none;
                subcontrol-position: bottom;
                subcontrol-origin: margin;
            }
            QScrollBar::sub-line:vertical {
                background: qlineargradient(x1:0, y1:0, x2:1, y2:0,
                stop: 0  rgba(64, 65, 79, 0), stop: 0.5 rgba(64, 65, 79, 0),  stop:1 rgba(64, 65, 79, 0));
                height: 0 px;
                border: none;
                subcontrol-position: top;
                subcontrol-origin: margin;
            }
            QScrollBar::sub-page:vertical {
            background: rgba(64, 65, 79, 0);
            }

            QScrollBar::add-page:vertical {
            background: rgba(64, 65, 79, 0);
            }
        """)

        self.term_input.setVerticalScrollBar(self.term_input_bar)

        # 改变默认滚动条
        self.explain_input_bar = QtWidgets.QScrollBar()
        self.explain_input_bar.setStyleSheet("""
            QScrollBar:vertical {
                border-width: 0px;
                border: none;
                background:rgba(64, 65, 79, 0);
                width:12px;
                margin: 0px 0px 0px 0px;
            }
            QScrollBar::handle:vertical {
                background: qlineargradient(x1:0, y1:0, x2:1, y2:0,
                stop: 0 #afc779, stop: 0.5 #afc779, stop:1 #afc779);
                min-height: 20px;
                max-height: 20px;
                margin: 0 0px 0 0px;
                border-radius: 6px;
            }
            QScrollBar::add-line:vertical {
                background: qlineargradient(x1:0, y1:0, x2:1, y2:0,
                stop: 0 rgba(64, 65, 79, 0), stop: 0.5 rgba(64, 65, 79, 0),  stop:1 rgba(64, 65, 79, 0));
                height: 0px;
                border: none;
                subcontrol-position: bottom;
                subcontrol-origin: margin;
            }
            QScrollBar::sub-line:vertical {
                background: qlineargradient(x1:0, y1:0, x2:1, y2:0,
                stop: 0  rgba(64, 65, 79, 0), stop: 0.5 rgba(64, 65, 79, 0),  stop:1 rgba(64, 65, 79, 0));
                height: 0 px;
                border: none;
                subcontrol-position: top;
                subcontrol-origin: margin;
            }
            QScrollBar::sub-page:vertical {
            background: rgba(64, 65, 79, 0);
            }

            QScrollBar::add-page:vertical {
            background: rgba(64, 65, 79, 0);
            }
        """)

        self.explain_input.setVerticalScrollBar(self.explain_input_bar)

        # 改变默认滚动条
        self.query_output_bar = QtWidgets.QScrollBar()
        self.query_output_bar.setStyleSheet("""
            QScrollBar:vertical {
                border-width: 0px;
                border: none;
                background:rgba(64, 65, 79, 0);
                width:12px;
                margin: 0px 0px 0px 0px;
            }
            QScrollBar::handle:vertical {
                background: qlineargradient(x1:0, y1:0, x2:1, y2:0,
                stop: 0 #afc779, stop: 0.5 #afc779, stop:1 #afc779);
                min-height: 20px;
                max-height: 20px;
                margin: 0 0px 0 0px;
                border-radius: 6px;
            }
            QScrollBar::add-line:vertical {
                background: qlineargradient(x1:0, y1:0, x2:1, y2:0,
                stop: 0 rgba(64, 65, 79, 0), stop: 0.5 rgba(64, 65, 79, 0),  stop:1 rgba(64, 65, 79, 0));
                height: 0px;
                border: none;
                subcontrol-position: bottom;
                subcontrol-origin: margin;
            }
            QScrollBar::sub-line:vertical {
                background: qlineargradient(x1:0, y1:0, x2:1, y2:0,
                stop: 0  rgba(64, 65, 79, 0), stop: 0.5 rgba(64, 65, 79, 0),  stop:1 rgba(64, 65, 79, 0));
                height: 0 px;
                border: none;
                subcontrol-position: top;
                subcontrol-origin: margin;
            }
            QScrollBar::sub-page:vertical {
            background: rgba(64, 65, 79, 0);
            }

            QScrollBar::add-page:vertical {
            background: rgba(64, 65, 79, 0);
            }
        """)

        self.query_output.setVerticalScrollBar(self.query_output_bar)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(2)
        self.close_btn.clicked.connect(MainWindow.close) # type: ignore
        self.minimise.clicked.connect(MainWindow.showMinimized) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.caption.setText(_translate("MainWindow", "LexiLab"))
        self.term_input.setPlaceholderText(_translate("MainWindow", "Input the term ..."))
        self.explain_input.setPlaceholderText(_translate("MainWindow", "Input the explanation of the term ..."))
        self.tips.setText(_translate("MainWindow", "欢迎来到LexiLab系统 ！"))
        self.query_input.setPlaceholderText(_translate("MainWindow", "Input the term ..."))
        self.show_record_num.setText(_translate("MainWindow", "记录总数"))
        self.show_username.setText(_translate("MainWindow", "TextLabel"))
        self.show_email.setText(_translate("MainWindow", "TextLabel"))
import resources_rc
